### ISSUE TITLE
Customize the placeholder during loading

### ISSUE THREAD

**Issue by ioanlucut** [stereobooster/react-ideal-image#142]
Hello! First, thank you for the library.

I'd like to ask if is possible to customize the placeholder **only** during loading of the placeholder.
I'd like to add a blur effect to the tiny image (lqip) so that it looks smoother. But if I do that, it is persisted also when the image is loaded.

**Comment by ioanlucut** [comment]
Hello! Could I provide a PR for this issue? Is it a valid use case for you?
Thank you.

**Comment by stereobooster** [comment]
Yes sure. You will change styles of the component, right?

**Comment by ioanlucut** [comment]
My raw idea is to be able to provide at least different styles for the `svg` and the `img`.
This would be the easiest solution, I think. What do you think?

**Comment by stereobooster** [comment]
Isn't it about adding style to lqip element? Not sure why you two of them

**Comment by ioanlucut** [comment]
Sorry for the confusion. I want to add the style to the placeholder, which is the wrapper of the img and svg.

**Comment by stereobooster** [comment]
I'm not sure why you need to style something else except lqip.

**Comment by ioanlucut** [comment]
I want to apply a CSS extra blur setting on the image while it gets loaded. And that has to be made on the parent, which is the placeholder.

So:
- Image gets loaded
- Show the background
- Show the lqip (svg)
- **In this moment I want to set a blur on the SVG**
- Load the normal image
- **Remove the blur from the placeholder, otherwise it gets shown on the image as well**
- Show the normal image

**Comment by stereobooster** [comment]
I'm not sure about the implementation, but the feature (ability to add extra blur) is ok

**Comment by scarletks1214** [comment]
I am one of react developers who loves react-ideal-image.
May I ask a question in the usage?

I want to have lqip placeholder of remote images.
Can I implement this feature?

Regards

**Comment by stereobooster** [comment]
> I want to have lqip placeholder of remote images.

What do you mean? Can you explain how it would work

**Comment by scarletks1214** [comment]
I want to build image list with remote url using react-ideal-image
images are not in local but in remote.(e.g. https://images.unsplash.com/photo-1555753360-4138be16d099?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1868&q=80)

In this case I can't import images since the images are on remote.
How can I use low quality image placeholder?

**Comment by stereobooster** [comment]
The idea of placeholder is that it is immediately available and the actual image is remote. Because image is remote we take precautions, like control loading or have preview. Remote previews kind of breaks the idea of previews. What you can do is to build previews upfront and return it with API response.
