### ISSUE TITLE
This repository needs tests

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-ideal-image#16]
* `react-ideal-image` version: N/A
* `node` version: N/A
* `npm` (or `yarn`) version: N/A

Relevant code or config

What you did:

What happened:

Reproduction repository:

**Problem description**: This repository needs tests

Suggested solution: Write some

**Comment by tvthatsme** [comment]
Do you know if anyone is working on this one? I'm working on a similar (simpler) library to yours and would enjoy learning from your approach by helping to write the tests.

**Comment by stereobooster** [comment]
I guess nobody works on this, because nobody said anything

**Comment by tvthatsme** [comment]
working on it 😀

**Comment by stereobooster** [comment]
Just in case, so we would be on the same page: you don't need to do all of them at once, you can create small PRs, even one test is better than nothing and thank you for doing it.

Initially there were simpler components, like Lazyload without all the network fluff, but I didn't figure out how to compose `IdeaImage` component out of them, so I removed it and wrote one big component.

**Comment by stereobooster** [comment]
Issue with canvas: to run tests we need canvas, but really small portion of it:
- we can mock it. See discussion here https://github.com/stereobooster/react-ideal-image/pull/31
- or we can use "real" one (`canvas-prebuilt`). See https://github.com/stereobooster/react-ideal-image/pull/18

**Comment by revanth0212** [comment]
@tvthatsme are you working on this? I would love to contribute some tests of my own. 

@stereobooster I realized this is a great component but to react even more people, tests are paramount. But a thing though. We may need to update react to `>= 16.8.0` and use `jest`. Also, there are certain changes to the components that I would like to propose. What do you think of those? And how do you think I should go about those changes? Shall I fork the current repo, make all the changes, updations and test and then create a PR?

This is a very useful component when it comes to PWAs.

**Comment by stereobooster** [comment]
@revanth0212 you can try to update to latest react and jest this should be straightforward, but switching to hook is not so trivial

**Comment by revanth0212** [comment]
I understand. I am not changing the code as of now. My goal, for now, is to reach a high level of code coverage using `jest`. Once we have that done, changing code can be of less pain because if something goes wrong, tests will catch them.

As of today, I am done with upgrading all the required packages to work with react `16.9.x` and tests for a couple of `loader.js` functions.

You can track my progress in this branch: https://github.com/revanth0212/react-ideal-image/tree/pr/codeRefactorAndTests

Let me know if something needs to be changed. I will be more than happy to make it happen.

**Comment by stereobooster** [comment]
> Once we have that done, changing code can be of less pain because if something goes wrong, tests will catch them.

Only if API stays the same, but with hooks it will change.

**Comment by revanth0212** [comment]
Most often it shouldn't, but if it looks like the API is changing, then I won't go ahead with refactoring. Also, we don't need to move to hooks unless an until needed since classes still work with React `16.9.x`.

But for now, I am only writing tests. No code changes.

**Comment by tvthatsme** [comment]
@revanth0212 I am no longer working on this - switched to use gatsby-image for work that I was interested in here.

You're free from my side to pick up where things left off.

Just one thing that you should probably know: the CI is failing because some snapshot diffs don't match. I know that we both looked at why this was happening but were never able to figure out why or how to fix it. Because of this, you can see that the build fails. You might want to look at that first in your additions.

**Comment by revanth0212** [comment]
@tvthatsme you are right. There were some snapshot tests that were failing. I tried upgrading the snapshots and they worked ever since. On the flip side, for some reason, the typescript tests that we have, are failing because babel is not able to understand them (`interface` is an example). I am trying to fix those now.
